### PR TITLE
Dark mode?

### PR DESCRIPTION
**Pull request by jer123se12**
and also more accurate word choice

it is scientifically proven that S4-01 > S4-07

### CODE REVIEW

**Comment by awpgikxdigj** [comment]
The table formatting is really cool but I'm getting a weird bug where the first table that gets returned is printed where the second table should be, the second where the third should be, and so on until the last table, which is printed under the credits. Can you confirm if this is happening on your side too?
Screen Shot 2022-08-11 at 6 31 38 PM

**Comment by awpgikxdigj** [comment]
oh yeah you also said today isnt working for you can you give me some details on that?

**Comment by jer123se12** [comment]
> oh yeah you also said today isnt working for you can you give me some details on that?

Oh I realized its my fault
My computer's time changed to like 4 days ago and that broke the thing. Fixed after updating my clock

**Comment by jer123se12** [comment]
> The table formatting is really cool but I'm getting a weird bug where the first table that gets returned is printed where the second table should be, the second where the third should be, and so on until the last table, which is printed under the credits. Can you confirm if this is happening on your side too?
> Screen Shot 2022-08-11 at 6 31 38 PM

Oh yes it happens on my side too... Did not notice that lol I thought it was supposed to be there

**Comment by awpgikxdigj** [comment]
do you mind if i just close this and then you work on the new version of the file

**Comment by jer123se12** [comment]
Ye sure idm

**Pull request closed without merging**
